### ISSUE TITLE
v0.8.6 fails to build on non-Windows/macOS/Linux

### ISSUE THREAD

**Issue by jbeich** [AOMediaCodec/SVT-AV1#1613]
Regressed by #1600. Fixing [upstream](https://github.com/pytorch/cpuinfo) is non-trivial due tons of platform-specific code.
```
$ cc --version
FreeBSD clang version 11.0.0 (git@github.com:llvm/llvm-project.git llvmorg-11.0.0-0-g176249bd673)
Target: x86_64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /usr/bin

$ cmake -B /tmp/SVT-AV1_build -G Ninja
$ cmake --build /tmp/SVT-AV1_build
[...]
FAILED: SVT-AV1/Bin/Release/SvtAv1DecApp
: && /usr/bin/cc -Wall -Wextra -Wformat -Wformat-security -fstack-protector-strong -D_FORTIFY_SOURCE=2 -O3 -DNDEBUG -pie -z noexecstack -z relro -z now Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/EbDecAppMain.c.o Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/EbDecParamParser.c.o Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/EbDecTime.c.o Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/EbFileUtils.c.o Source/App/DecApp/CMakeFiles/SvtAv1DecApp.dir/EbMD5Utility.c.o -o SVT-AV1/Bin/Release/SvtAv1DecApp  -Wl,-rpath,SVT-AV1/Bin/Release:  SVT-AV1/Bin/Release/libSvtAv1Dec.so.0.8.6  -lpthread  -lm  -lpthread && :
ld: error: SVT-AV1/Bin/Release/libSvtAv1Dec.so.0.8.6: undefined reference to cpuinfo_isa [--no-allow-shlib-undefined]
cc: error: linker command failed with exit code 1 (use -v to see invocation)
[267/270] Building C object Source/Lib/Encoder/ASM_AVX2/CMakeFiles/ENCODER_ASM_AVX2.dir/highbd_fwd_txfm_avx2.c.o
ninja: build stopped: subcommand failed.
```

**Comment by jbeich** [comment]
@yurivict, how did you work around https://github.com/pytorch/pytorch/issues/28772? If you gave up did encounter any other software depending on cpuinfo from pytorch?

**Comment by yurivict** [comment]
@jbeich I think that this library wasn't linked: https://github.com/pytorch/cpuinfo

**Comment by jbeich** [comment]
@yurivict, cpuinfo doesn't have code for FreeBSD:
```
$ git clone https://github.com/pytorch/cpuinfo
$ cmake -B cpuinfo_build -G Ninja -S cpuinfo
[...]
CMake Warning at CMakeLists.txt:71 (MESSAGE):
  Target processor architecture "amd64" is not supported in cpuinfo.  cpuinfo
  will compile, but cpuinfo_initialize() will always fail.

CMake Warning at CMakeLists.txt:84 (MESSAGE):
  Target operating system "FreeBSD" is not supported in cpuinfo.  cpuinfo
  will compile, but cpuinfo_initialize() will always fail.
[...]
$ cmake --build cpuinfo_build
$ nm cpuinfo_build/libcpuinfo.a | fgrep cpuinfo_isa || echo "not found"
not found
```

**Comment by jbeich** [comment]
Did pytorch really work with cpuinfo that lacks `cpuinfo_isa`?

**Comment by yurivict** [comment]
@jbeich I had to patch its CMakeLists.txt, possibly to remove ```cpuinfo```, but I don't remember the specifics.
```cpuinfo``` only provides CPU stats and isn't critical for ```pytorch```.

**Comment by brad0** [comment]
OpenBSD port maintainer here. Also ran into this.

**Comment by hassount** [comment]
Hi all, is this still an issue or did #1648 address it ?
